version: '3.9'

volumes:
  database:
    name: mariadb_volume
    driver_opts:
      device: Users/jihyjeon/data/mariadb
      o: bind
      type: none
  website:
    name: wordpress_volume
    driver_opts:
      device: Users/jihyjeon/data/wordpress
      o: bind
      type: none

services:
    mariadb:
      container_name: mariadb
      build: ./requirements/mariadb
      image: mariadb:42
      restart: always
      # image: debian:bullseye
      expose:
        - "3306"
      volumes:
        - database:/var/lib/mysql
      networks:
        - inception
      env_file:
        - .env
      tty: true
      # init: true

    # nginx:
    #   container_name: nginx
    #   build: ./requirements/nginx
    #   image: nginx:42
    #   restart: always
    #   ports:
    #     - "443:443"
    #   volumes:
    #     - website:/var/www/html
    #   networks:
    #     - inception
    #   env_file:
    #     - .env
    #   tty: true
    #   init: true

    # wordpress:
    #   container_name: wordpress
    #   image: debian:bullseye
    #   # build: ./requirements/wordpress
    #   # image: wordpress:42
    #   restart: always
    #   volumes:
    #     - website:/var/www/html
    #   expose: 
    #     - "9000"
    #   networks:
    #     - inception
    #   env_file:
    #     - .env
    #   tty: true
    #   # init: true

networks:
    inception:
        driver: bridge