version: '3.5'

volumes:
  database:
    name: mariadb_volume
    driver: local
    driver_opts:
      device: ${HOME:-/home/jihyjeon}/data/mariadb
      o: bind
      type: none
  website:
    name: wordpress_volume
    driver: local
    driver_opts:
      device: ${HOME:-/home/jihyjeon}/data/wordpress
      o: bind
      type: none

services:
    mariadb:
      container_name: mariadb
      build: ./requirements/mariadb
      image: mariadb:42
      restart: always
      # image: debian:bullseye
      expose:
        - "3306"
      volumes:
        - database:/var/lib/mysql
      networks:
        - inception
      env_file:
        - .env
      tty: true

    nginx:
      container_name: nginx
      build: ./requirements/nginx
      image: nginx:42
      restart: always
      ports:
        - "443:443"
      volumes:
        - website:/var/www/html
      networks:
        - inception
      env_file:
        - .env
      tty: true

    wordpress:
      container_name: wordpress
      build: ./requirements/wordpress
      image: wordpress:42
      restart: always
      volumes:
        - website:/var/www/html
      expose: 
        - "9000"
      networks:
        - inception
      env_file:
        - .env
      tty: true

networks:
    inception:
        driver: bridge