version: '3.9'

volumes:
  database:
    name: mariadb_volume
    driver_opts:
      device: Users/jihyjeon/data/mariadb
      o: bind
      type: none
  website:
    name: wordpress_volume
    driver_opts:
      device: Users/jihyjeon/data/wordpress
      o: bind
      type: none

services:
    mariadb:
      container_name: mariadb
      build: ./requirements/mariadb
      image: mariadb:42
      restart: on-failure
      # image: debian:bullseye
      expose:
        - "3306"
      volumes:
        - database:/var/lib/mysql
      networks:
        - inception
      env_file:
        - .env
      tty: true
      # init: true
      healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
        interval: 10s
        timeout: 5s
        retries: 5
        start_period: 30s

    # nginx:
    #   container_name: nginx
    #   build: ./requirements/nginx
    #   image: nginx:42
    #   restart: on-failure
    #   ports:
    #     - "443:443"
    #   volumes:
    #     - website:/var/www/html
    #   networks:
    #     - inception
    #   depends_on:
    #     - mariadb
    #     - wordpress
    #   env_file:
    #     - .env
    #   tty: true
    #   # init: true
    #   healthcheck:
    #     test: ["CMD", "nginx", "-t"]
    #     interval: 30s
    #     timeout: 10s
    #     retries: 3
    #     start_period: 30s

    wordpress:
      container_name: wordpress
      build: ./requirements/wordpress
      image: wordpress:42
      restart: on-failure
      depends_on: 
        - mariadb
      volumes:
        - website:/var/www/html
      expose: 
        - "9000"
      networks:
        - inception
      env_file:
        - .env
      tty: true
      healthcheck:
        test: ["CMD", "php-fpm82", "-t"]
        interval: 30s
        timeout: 10s
        retries: 3
        start_period: 30s
    #   # init: true

networks:
    inception:
        driver: bridge